name: 'build'

on:
  workflow_dispatch:
    inputs:
      optional_deps:
        description: 'optional_deps=pkg-A:optional-dep-B,pkg-C:optional-dep-D'
        default: ''
        required: false
        type: string
      context:
        description: 'Extra information from invoker'
        default: ''
        required: false
        type: string
  schedule:
    - cron: '0 0/2 * * *'

env:
  PYTHONUNBUFFERED: 1

permissions: {}

jobs:

  schedule:
    if: ${{ github.ref == 'refs/heads/main' }}
    timeout-minutes: 360
    runs-on: ubuntu-24.04

    environment:
      name: build
      deployment: false

    permissions:
      contents: write
      actions: write

    steps:

    - name: Dump inputs
      if: ${{ github.event_name == 'workflow_dispatch' }}
      env:
        CONTEXT: '${{ toJSON(github.event.inputs) }}'
      run: |
        echo "$CONTEXT"

    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        persist-credentials: false

    - name: Cache pip dependencies
      uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install deps
      env:
        PIP_DISABLE_PIP_VERSION_CHECK: 1
      run: |
        python3 -m venv .venv
        source .venv/bin/activate
        python3 -m pip install -r requirements.txt
        echo "$VIRTUAL_ENV/bin" >> $GITHUB_PATH

    - name: Plan, dispatch, and supervise build jobs
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        OPTIONAL_DEPS: ${{ github.event.inputs.optional_deps }}
      run: |
        python -m msys2_autobuild supervise --optional-deps "$OPTIONAL_DEPS" --target-branch "build-branch"
